# Generated by Django 6.1.1 on 2026-09-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_birth_date_user_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_sector',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='civility',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
