# Generated by Django 6.1.1 on 2026-09-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_seed_congo_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('login', 'Login')], default='registration', max_length=20),
        ),
    ]
