# Generated by Django 6.1.1 on 2026-09-27 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userapitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='custom', max_length=30)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('security', models.CharField(choices=[('tls', 'STARTTLS'), ('ssl', 'SSL/TLS'), ('none', 'Aucun')], default='tls', max_length=10)),
                ('encrypted_password', models.TextField(blank=True)),
                ('signature', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='smtp_configuration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
