# Generated by Django 6.1.1 on 2026-10-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_supportticket_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
