"""
Django settings for sms_platform project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(path):
    """Load a simple local .env file without overriding real environment variables."""
    if not path.is_file():
        return
    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#'):
            continue
        if line.startswith('export '):
            line = line[7:].lstrip()
        name, separator, value = line.partition('=')
        if not separator or not name.strip():
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
            value = value[1:-1]
        os.environ.setdefault(name.strip(), value)


_load_env_file(BASE_DIR / '.env')


def _env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def _env_list(name, default=''):
    return [item.strip() for item in os.getenv(name, default).split(',') if item.strip()]


SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    raise ImproperlyConfigured('Set DJANGO_SECRET_KEY in the environment or local .env file.')

DEBUG = _env_bool('DJANGO_DEBUG', False)
ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1' if DEBUG else '')
if not ALLOWED_HOSTS:
    raise ImproperlyConfigured('Set DJANGO_ALLOWED_HOSTS to the hostnames served by this site.')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# SMS provider configuration
SMS_API_TOKEN = os.getenv('SMS_API_TOKEN', '')
SMS_API_URL = os.getenv('SMS_API_URL', 'https://sms.mtncongo.net/api/sms/')
SMS_AUTH_SCHEME = 'Token'
SMS_SENDER = os.getenv('SMS_SENDER', 'ElemboTech')
SMTP_ENCRYPTION_KEY = os.getenv('SMTP_ENCRYPTION_KEY', '')

# MTN MoMo Collections. Leave credentials empty until provisioned by MTN.
MOMO_API_BASE_URL = os.getenv('MOMO_API_BASE_URL', 'https://sandbox.momodeveloper.mtn.com').rstrip('/')
MOMO_TARGET_ENVIRONMENT = os.getenv('MOMO_TARGET_ENVIRONMENT', 'sandbox')
MOMO_COLLECTION_SUBSCRIPTION_KEY = os.getenv('MOMO_COLLECTION_SUBSCRIPTION_KEY', '')
MOMO_API_USER = os.getenv('MOMO_API_USER', '')
MOMO_API_KEY = os.getenv('MOMO_API_KEY', '')
MOMO_CURRENCY = os.getenv('MOMO_CURRENCY', 'XAF')
MOMO_REQUEST_TIMEOUT = 15

# Airtel Money Congo-B collections. Credentials are provisioned in the Airtel developer portal.
AIRTEL_API_BASE_URL = os.getenv('AIRTEL_API_BASE_URL', 'https://openapiuat.airtel.africa').rstrip('/')
AIRTEL_CLIENT_ID = os.getenv('AIRTEL_CLIENT_ID', '')
AIRTEL_CLIENT_SECRET = os.getenv('AIRTEL_CLIENT_SECRET', '')
AIRTEL_COUNTRY_CODE = os.getenv('AIRTEL_COUNTRY_CODE', 'CG')
AIRTEL_CURRENCY = os.getenv('AIRTEL_CURRENCY', 'XAF')
AIRTEL_REQUEST_TIMEOUT = 15


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',

    'users',
    'contacts',
    'campaigns',
    'billing',
    'support',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sms_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.account_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'sms_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# SQL Server connection settings. Do not commit real credentials.
SQLSERVER_HOST = os.getenv('SQLSERVER_HOST', '')
SQLSERVER_NAME = os.getenv('SQLSERVER_NAME', '')
SQLSERVER_USER = os.getenv('SQLSERVER_USER', '')
SQLSERVER_PASSWORD = os.getenv('SQLSERVER_PASSWORD', '')
SQLSERVER_PORT = os.getenv('SQLSERVER_PORT', '1433')

missing_sqlserver_settings = [
    name for name, value in {
        'SQLSERVER_HOST': SQLSERVER_HOST,
        'SQLSERVER_NAME': SQLSERVER_NAME,
        'SQLSERVER_USER': SQLSERVER_USER,
        'SQLSERVER_PASSWORD': SQLSERVER_PASSWORD,
        'SQLSERVER_PORT': SQLSERVER_PORT,   
    }.items() if not value
]

if missing_sqlserver_settings:
    raise ImproperlyConfigured(
        'SQL Server is the only supported database. Set: '
        + ', '.join(missing_sqlserver_settings)
    )

if not DEBUG:
    SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', True)
    SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', True)
    CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', True)
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', True)
    SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', True)

CSRF_TRUSTED_ORIGINS = _env_list('CSRF_TRUSTED_ORIGINS')

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': SQLSERVER_NAME,
        'USER': SQLSERVER_USER,
        'PASSWORD': SQLSERVER_PASSWORD,
        'HOST': SQLSERVER_HOST,
        'PORT': SQLSERVER_PORT,
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'encrypt': 'yes',
            'extra_params': 'TrustServerCertificate=yes',
            'host_is_server': 'true',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Brazzaville'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.authentication.UserAPITokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]
